version: '3.9'

services:

  front:
    image: sermalenk/skypro-front:lesson-36
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

  collect_static:
    image: ${DOCKERHUB_USER}/todolist:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/app/static/

  api:
    image: ${DOCKERHUB_USER}/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully



  migrations:
    image: ${DOCKERHUB_USER}/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  django_static: